### ISSUE TITLE
创建角色时报错

### ISSUE THREAD

**Issue by ACaiCat** [zzp198/SSC#8]

**Comment by ACaiCat** [comment]
使用服务端开服，有hero's mod

**Comment by zzp198** [comment]
报错信息发一下，大部分都是某些mod不兼容导致的

**Comment by ACaiCat** [comment]
[11:05:10.108] [Main Thread/INFO] [Terraria]: 76561199238567735已加入。
[11:05:27.573] [Main Thread/WARN] [tML]: 静默捕获异常: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImproveGame.Common.Players.DataPlayer.SaveData(TagCompound tag) in ImproveGame\Common\Players\DataPlayer.cs:line 74
   at Terraria.ModLoader.IO.PlayerIO.SaveModData(Player player) in tModLoader\Terraria\ModLoader\IO\PlayerIO.cs:line 179
   at Terraria.ModLoader.IO.PlayerIO.SaveData(Player player) in tModLoader\Terraria\ModLoader\IO\PlayerIO.cs:line 36
   at DMD<Terraria.Player::InternalSavePlayerFile>(PlayerFileData playerFile)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at QOS.QOSKit.<>c__DisplayClass1_0.<InternalSavePlayer>b__0() in QOSKit.cs:line 36
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 170
   at QOS.Common.Systems.SSCSystem.HandlePacket_CreateSSC(BinaryReader bin, Int32 plr) in QOS\Common\Systems\SSCSystem.cs:line 332
   at Terraria.ModLoader.ModNet.HandleModPacket(BinaryReader reader, Int32 whoAmI, Int32 length) in tModLoader\Terraria\ModLoader\ModNet.cs:line 485
   at DMD<Terraria.MessageBuffer::GetData>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex) in tModLoader\Terraria\NetMessage.cs:line 2237
   at Terraria.Netplay.UpdateServerInMainThread() in tModLoader\Terraria\Netplay.cs:line 65
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12834
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at ImproveGame.Common.Systems.NetPasswordSystem.CheckConnected(orig_Update orig, Main self, GameTime gameTime) in ImproveGame\Common\Systems\NetPasswordSystem.cs:line 18
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4678
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4214
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 233
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at System.Threading.Thread.StartCallback()

**Comment by ACaiCat** [comment]
使用仓库的源码(10.1)打包的mod没有问题

**Comment by ACaiCat** [comment]
行吧，其实10.1的mod和10.8的mod混着用好像没有啥事情
