### ISSUE TITLE
数据包太大

### ISSUE THREAD

**Issue by ACaiCat** [zzp198/SSC#9]
报错:
```
[22:20:24.877] [Main Thread/WARN] [tML]: 静默捕获异常: 
System.Exception: 数据包太大 131049 > 65535
   at Terraria.ModLoader.ModPacket.Finish() in tModLoader\Terraria\ModLoader\ModPacket.cs:line 57
   at Terraria.ModLoader.ModPacket.Send(Int32 toClient, Int32 ignoreClient) in tModLoader\Terraria\ModLoader\ModPacket.cs:line 29
   at SSC.Common.Systems.NetworkSystem.ChooseSSC(BinaryReader bin, Int32 plr) in SSC\Common\Systems\NetworkSystem.cs:line 176
   at SSC.Common.SSC.HandlePacket(BinaryReader bin, Int32 plr) in SSC.cs:line 38
   at Terraria.ModLoader.ModNet.HandleModPacket(BinaryReader reader, Int32 whoAmI, Int32 length) in tModLoader\Terraria\ModLoader\ModNet.cs:line 486
   at DMD<Terraria.MessageBuffer::GetData>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex) in tModLoader\Terraria\NetMessage.cs:line 2237
   at Terraria.Netplay.UpdateServerInMainThread() in tModLoader\Terraria\Netplay.cs:line 65
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12834
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at ImproveGame.Common.Systems.NetPasswordSystem.CheckConnected(orig_Update orig, Main self, GameTime gameTime) in ImproveGame\Common\Systems\NetPasswordSystem.cs:line 18
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4678
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4214
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 233
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at System.Threading.Thread.StartCallback()

```
保存人物时也有报错，同样是数据包过大

**Comment by zzp198** [comment]
这需要改变底层的发包规则，改成分段传输，我会在下个版本加上。

**Comment by ACaiCat** [comment]
好的，十分感谢
